# Generated by Django 4.2.4 on 2023-08-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_baseemployeedata_remove_employee_base_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseemployeedata',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='baseemployeedata',
            name='last_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
