# Generated by Django 4.2.4 on 2023-08-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_remove_employee_first_name_remove_employee_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='base_data',
        ),
        migrations.AddField(
            model_name='employee',
            name='base_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='fte_percentage',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='BaseEmployeeData',
        ),
    ]
